### PR TITLE
feat: update /open-design content

### PR DESCRIPTION
**Pull request by cedrycm**
This PR covers a few changes mentions in issue https://github.com/BSA-US/dual-power-app/issues/89: 

- [x] Replace "Open Design" with "Open Design + Build" in app header (nav link)
- [x] Replace "Open Design" with "Open Design + Build" in page header (the big guy)
- [x] Remove "with Manhattan Hydraulics"
- [x] Added svg files and icons for BSA and MH 
- [x] Updated about section to reflect current dev process
- [x] Added useBreakpoints hook for responsive elements
- [x] Add yarn2 compatibility
- [x] add in unplugin-icons, unplugin-auto-import

### CODE REVIEW

**Comment by cedrycm** [comment]
@replygirl  I added some extra config options to webpack for unplugin-icons + unplugin-auto-import for us to import our custom image assets under the 'custom' collection: 
`import BSAGlyph from '~icons/custom/bsa-glyph.jsx'`

with auto-import we can also choose not to explicitly import these and use this notation instead: 
`IconBsaGlyph` 
which will generate global types into the [auto-imports.d.ts](https://github.com/BSA-US/dual-power-app/blob/0be4a63680fdc76857cd726605ef40dbeded1774/auto-imports.d.ts) file. 

note: 
this file also contains globals for react hooks which could be nice imo but can be removed if needed!
I also chose not to do an auto-import implementation in this PR due to a linting error that's set for jsx imports. not sure if that was something that could break the vercel deployment 🤷🏾

**Comment by replygirl** [comment]
getting there! quick notes
- we can use something above the fold for "show more", either the first paragraph or the first two
- we should only need the "show more" break on mobile
- four paragraphs at the same size, evenly spaced, looks like a lot. possible changes:
  - make it looks like two separate blocks by adding empty space or a divider
  - put the notes for designers + engineers in an outlined box (maybe the "show more" is expanding that box?)
  - use different opacities or sizes
- i would left-align the logos. possible approaches:
  - add `justify-content-start` or some other combo of grid layout utils
  - add `grid-cols-[auto,1fr]`
  - replace grid with `stack-x`

**Comment by cedrycm** [comment]
thanks for the feedback! i'll go ahead make those changes 🤝

**Comment by cedrycm** [comment]
that final rebase hurt took years off my life 🧎🏾

**Comment by replygirl** [comment]
in the live deployment click on the documents tab opens one of the documents immediately for some reason

**Comment by replygirl** [comment]
i think i might just need to wipe out those merges and rebase properly. luckily you already did the difficult part of the rebase :)

**Comment by cedrycm** [comment]
my bad! looks like i changed the img tag. should be fixed now!

**Review by replygirl — APPROVED** [review]

**Pull request merged**
